[project]
name = "particlemind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "awkward>=2.8.9",
    "fastjet>=3.5.1.1",
    "h5py>=3.15.1",
    "hydra-colorlog>=1.2.0",
    "hydra-core>=1.3.2",
    "ipykernel>=7.0.1",
    "jupyterlab>=4.4.10",
    "kaleido>=1.1.0",
    "lightning>=2.5.5",
    "lmdb>=1.7.5",
    "matplotlib>=3.10.7",
    "nbdev>=2.4.6",
    "nbformat>=5.10.4",
    "numpy>=2.3.4",
    "omegaconf>=2.3.0",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pre-commit>=4.3.0",
    "pyarrow>=22.0.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "tensorboardx>=2.6.4",
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "torchvision==0.20.1",
    "tqdm>=4.67.1",
    "uproot>=5.6.6",
    "vector>=1.7.0",
]
