[project]
name = "particlemind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "awkward>=2.8.10",
    "fastjet>=3.5.1.2",
    "h5py>=3.15.1",
    "ipykernel>=7.1.0",
    "jupyterlab>=4.4.10",
    "kaleido>=1.2.0",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "plotly>=6.4.0",
    "pre-commit>=4.4.0",
    "pyarrow>=22.0.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "torchvision==0.20.1",
    "tqdm>=4.67.1",
    "uproot>=5.6.8",
    "vector>=1.7.0",
]
